# Generated by Django 3.2.25 on 2026-06-27 10:19

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TourSession',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('owner_subject', models.CharField(max_length=64)),
                ('guest_token_hash', models.CharField(max_length=128, unique=True)),
                ('tour_slug', models.CharField(max_length=100)),
                ('language', models.CharField(max_length=10)),
                ('livekit_room', models.CharField(max_length=100)),
                ('participant_identity', models.CharField(max_length=100)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='TourStateCheckpoint',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('event_id', models.CharField(max_length=64)),
                ('event_type', models.CharField(max_length=100)),
                ('state_version', models.IntegerField()),
                ('active_mode', models.CharField(max_length=50)),
                ('current_beat_id', models.CharField(blank=True, max_length=100, null=True)),
                ('safe_anchor', models.JSONField(blank=True, null=True)),
                ('state_payload', models.JSONField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkpoints', to='tours.toursession')),
            ],
            options={
                'ordering': ['state_version'],
            },
        ),
        migrations.CreateModel(
            name='RecognitionEvent',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('request_event_id', models.CharField(max_length=64)),
                ('idempotency_key', models.CharField(max_length=128)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('file_name', models.CharField(max_length=255)),
                ('content_type', models.CharField(blank=True, max_length=100, null=True)),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('result_payload', models.JSONField(blank=True, null=True)),
                ('error_code', models.CharField(blank=True, max_length=100, null=True)),
                ('retryable', models.BooleanField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recognitions', to='tours.toursession')),
            ],
        ),
        migrations.CreateModel(
            name='EvalEvent',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('event_id', models.CharField(max_length=64)),
                ('event_type', models.CharField(max_length=100)),
                ('payload', models.JSONField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eval_events', to='tours.toursession')),
            ],
        ),
    ]
