# Generated by Django 3.2.25 on 2026-06-21 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_paymentmethod'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='duration_months',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
