# Generated by Django 6.0.6 on 2026-06-26 11:43

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_paymentmethod'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentmethod',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('1000.00'), max_digits=10),
        ),
    ]
