# Generated by Django 3.2.25 on 2026-06-25 10:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Governorate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('latitude', models.FloatField(help_text='Center latitude for radius queries')),
                ('longitude', models.FloatField(help_text='Center longitude for radius queries')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=100)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('cuisine', models.CharField(max_length=100)),
                ('average_meal_cost', models.IntegerField(help_text='Average cost of a meal in EGP')),
                ('rating', models.FloatField()),
                ('specialty', models.CharField(blank=True, max_length=200)),
                ('governorate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restaurants', to='attractions.governorate')),
            ],
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=100)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('price_per_night', models.IntegerField(help_text='Cost per night in EGP')),
                ('rating', models.FloatField()),
                ('category', models.CharField(choices=[('budget', 'Budget'), ('mid-range', 'Mid-range'), ('luxury', 'Luxury')], max_length=20)),
                ('governorate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotels', to='attractions.governorate')),
            ],
        ),
        migrations.CreateModel(
            name='Attraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=100)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('categories', models.JSONField(default=list, help_text='e.g. ["history", "culture"]')),
                ('average_cost', models.IntegerField(help_text='Cost in EGP')),
                ('visit_duration_hours', models.FloatField(default=2.0)),
                ('opening_time', models.TimeField(blank=True, null=True)),
                ('closing_time', models.TimeField(blank=True, null=True)),
                ('closed_on', models.JSONField(default=list, help_text='e.g. ["Friday"]')),
                ('best_time', models.CharField(blank=True, default='morning', max_length=20)),
                ('popularity', models.IntegerField(default=3)),
                ('description', models.TextField(blank=True)),
                ('governorate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attractions', to='attractions.governorate')),
            ],
        ),
    ]
