# Generated by Django 3.2.25 on 2026-06-25 10:54

from django.db import migrations
import datetime

def seed_data(apps, schema_editor):
    Governorate = apps.get_model('attractions', 'Governorate')
    Attraction = apps.get_model('attractions', 'Attraction')
    Hotel = apps.get_model('attractions', 'Hotel')
    Restaurant = apps.get_model('attractions', 'Restaurant')

    # Seed Governorates
    govs_data = [
        {"id": 1, "name": "Cairo", "latitude": 30.0444, "longitude": 31.2357},
        {"id": 2, "name": "Alexandria", "latitude": 31.2001, "longitude": 29.9187},
        {"id": 3, "name": "Luxor", "latitude": 25.6872, "longitude": 32.6396},
        {"id": 4, "name": "Aswan", "latitude": 24.0889, "longitude": 32.8998},
        {"id": 5, "name": "Giza", "latitude": 29.9870, "longitude": 31.2118},
        {"id": 6, "name": "Hurghada", "latitude": 27.2579, "longitude": 33.8116},
        {"id": 7, "name": "Sharm El-Sheikh", "latitude": 27.9158, "longitude": 34.3299},
        {"id": 8, "name": "Dahab", "latitude": 28.5010, "longitude": 34.5160},
        {"id": 9, "name": "Marsa Matruh", "latitude": 31.3547, "longitude": 27.2373},
        {"id": 10, "name": "Siwa", "latitude": 29.2032, "longitude": 25.5195},
    ]

    gov_map = {}
    for g in govs_data:
        gov, created = Governorate.objects.update_or_create(
            id=g["id"],
            defaults={"name": g["name"], "latitude": g["latitude"], "longitude": g["longitude"]}
        )
        gov_map[g["name"]] = gov

    # Seed Cairo & Giza Attractions (from egypt_places.json)
    cairo_giza_attractions = [
        {
            "name": "Pyramids of Giza",
            "gov_name": "Giza",
            "city": "Giza",
            "categories": ["history", "culture"],
            "average_cost": 700,
            "visit_duration_hours": 3.0,
            "opening_time": datetime.time(8, 0),
            "closing_time": datetime.time(17, 0),
            "best_time": "morning",
            "popularity": 5,
            "latitude": 29.9792,
            "longitude": 31.1342,
            "description": "The Giza Necropolis, including the Pyramids of Giza, the Great Sphinx, several cemeteries, a workers' village and an industrial complex."
        },
        {
            "name": "Egyptian Museum",
            "gov_name": "Cairo",
            "city": "Cairo",
            "categories": ["history", "museum"],
            "average_cost": 550,
            "visit_duration_hours": 2.0,
            "opening_time": datetime.time(9, 0),
            "closing_time": datetime.time(17, 0),
            "best_time": "afternoon",
            "popularity": 4,
            "latitude": 30.0478,
            "longitude": 31.2336,
            "description": "The Museum of Egyptian Antiquities, known commonly as the Egyptian Museum or Museum of Cairo, is home to an extensive collection of ancient Egyptian antiquities."
        },
        {
            "name": "Khan El Khalili",
            "gov_name": "Cairo",
            "city": "Cairo",
            "categories": ["shopping", "culture"],
            "average_cost": 0,
            "visit_duration_hours": 2.0,
            "opening_time": datetime.time(10, 0),
            "closing_time": datetime.time(23, 0),
            "best_time": "evening",
            "popularity": 5,
            "latitude": 30.0489,
            "longitude": 31.2622,
            "description": "A famous bazaar and souq in the historic center of Cairo, Egypt. Established as a center of trade in the Mamluk era."
        },
        {
            "name": "Citadel of Saladin",
            "gov_name": "Cairo",
            "city": "Cairo",
            "categories": ["history", "architecture"],
            "average_cost": 550,
            "visit_duration_hours": 2.0,
            "opening_time": datetime.time(9, 0),
            "closing_time": datetime.time(17, 0),
            "best_time": "morning",
            "popularity": 4,
            "latitude": 30.0296,
            "longitude": 31.2600,
            "description": "A medieval Islamic-era fortification in Cairo, Egypt, built by Salah ad-Din and further developed by subsequent Egyptian rulers."
        },
        {
            "name": "Al-Azhar Mosque",
            "gov_name": "Cairo",
            "city": "Cairo",
            "categories": ["religion", "architecture"],
            "average_cost": 0,
            "visit_duration_hours": 1.0,
            "opening_time": datetime.time(4, 0),
            "closing_time": datetime.time(22, 0),
            "best_time": "morning",
            "popularity": 4,
            "latitude": 30.0456,
            "longitude": 31.2633,
            "description": "An Islamic temple in Cairo, Egypt. Al-Mu'izz li-Din Allah of the Fatimid Caliphate commissioned its construction for the newly established capital city in 970."
        },
        {
            "name": "Nile River Cruise",
            "gov_name": "Cairo",
            "city": "Cairo",
            "categories": ["entertainment", "relaxation"],
            "average_cost": 1500,
            "visit_duration_hours": 2.0,
            "opening_time": datetime.time(18, 0),
            "closing_time": datetime.time(22, 0),
            "best_time": "evening",
            "popularity": 5,
            "latitude": 30.0444,
            "longitude": 31.2357,
            "description": "A relaxing cruise along the Nile River in Cairo, usually featuring traditional food, music, and dance performances."
        },
        {
            "name": "Coptic Museum",
            "gov_name": "Cairo",
            "city": "Cairo",
            "categories": ["history", "museum"],
            "average_cost": 280,
            "visit_duration_hours": 2.0,
            "opening_time": datetime.time(9, 0),
            "closing_time": datetime.time(17, 0),
            "best_time": "afternoon",
            "popularity": 3,
            "latitude": 30.0059,
            "longitude": 31.2304,
            "description": "A museum in Coptic Cairo, Egypt, with the largest collection of Coptic Christian artifacts in the world."
        }
    ]

    # Seed Luxor, Alexandria, Hurghada Attractions
    other_attractions = [
        # Luxor
        {
            "name": "Karnak Temple",
            "gov_name": "Luxor",
            "city": "Luxor",
            "categories": ["history", "culture", "architecture"],
            "average_cost": 450,
            "visit_duration_hours": 2.5,
            "opening_time": datetime.time(6, 0),
            "closing_time": datetime.time(17, 30),
            "best_time": "morning",
            "popularity": 5,
            "latitude": 25.7188,
            "longitude": 32.6586,
            "description": "The Karnak Temple Complex comprises a vast mix of decayed temples, pylons, chapels, and other buildings near Luxor."
        },
        {
            "name": "Valley of the Kings",
            "gov_name": "Luxor",
            "city": "Luxor",
            "categories": ["history", "culture"],
            "average_cost": 600,
            "visit_duration_hours": 3.0,
            "opening_time": datetime.time(6, 0),
            "closing_time": datetime.time(16, 0),
            "best_time": "morning",
            "popularity": 5,
            "latitude": 25.7401,
            "longitude": 32.6018,
            "description": "A valley in Egypt where, for a period of nearly 500 years from the 16th to 11th century BC, rock-cut tombs were excavated for the pharaohs."
        },
        {
            "name": "Luxor Temple",
            "gov_name": "Luxor",
            "city": "Luxor",
            "categories": ["history", "culture", "architecture"],
            "average_cost": 400,
            "visit_duration_hours": 1.5,
            "opening_time": datetime.time(6, 0),
            "closing_time": datetime.time(22, 0),
            "best_time": "evening",
            "popularity": 5,
            "latitude": 25.6995,
            "longitude": 32.6394,
            "description": "A large Ancient Egyptian temple complex located on the east bank of the Nile River in the city today known as Luxor."
        },
        {
            "name": "Temple of Hatshepsut",
            "gov_name": "Luxor",
            "city": "Luxor",
            "categories": ["history", "architecture"],
            "average_cost": 360,
            "visit_duration_hours": 2.0,
            "opening_time": datetime.time(6, 0),
            "closing_time": datetime.time(17, 0),
            "best_time": "morning",
            "popularity": 4,
            "latitude": 25.7382,
            "longitude": 32.6074,
            "description": "The Mortuary Temple of Hatshepsut is a mortuary temple of Ancient Egypt built for the Eighteenth Dynasty pharaoh Hatshepsut."
        },
        {
            "name": "Colossi of Memnon",
            "gov_name": "Luxor",
            "city": "Luxor",
            "categories": ["history"],
            "average_cost": 0,
            "visit_duration_hours": 0.5,
            "opening_time": datetime.time(0, 0),
            "closing_time": datetime.time(23, 59),
            "best_time": "afternoon",
            "popularity": 4,
            "latitude": 25.7211,
            "longitude": 32.6064,
            "description": "Two massive stone statues of the Pharaoh Amenhotep III, who reigned in Egypt during the Dynasty XVIII."
        },
        # Alexandria
        {
            "name": "Citadel of Qaitbay",
            "gov_name": "Alexandria",
            "city": "Alexandria",
            "categories": ["history", "architecture"],
            "average_cost": 300,
            "visit_duration_hours": 2.0,
            "opening_time": datetime.time(9, 0),
            "closing_time": datetime.time(17, 0),
            "best_time": "morning",
            "popularity": 5,
            "latitude": 31.2131,
            "longitude": 29.8856,
            "description": "A 15th-century defensive fortress located on the Mediterranean sea coast, in Alexandria, Egypt."
        },
        {
            "name": "Bibliotheca Alexandrina",
            "gov_name": "Alexandria",
            "city": "Alexandria",
            "categories": ["culture", "museum", "architecture"],
            "average_cost": 300,
            "visit_duration_hours": 3.0,
            "opening_time": datetime.time(9, 0),
            "closing_time": datetime.time(19, 0),
            "best_time": "afternoon",
            "popularity": 5,
            "latitude": 31.2089,
            "longitude": 29.9092,
            "description": "A major library and cultural center on the shore of the Mediterranean Sea in the Egyptian city of Alexandria."
        },
        {
            "name": "Montaza Palace Gardens",
            "gov_name": "Alexandria",
            "city": "Alexandria",
            "categories": ["nature", "relaxation", "architecture"],
            "average_cost": 50,
            "visit_duration_hours": 3.0,
            "opening_time": datetime.time(8, 0),
            "closing_time": datetime.time(0, 0),
            "best_time": "afternoon",
            "popularity": 4,
            "latitude": 31.2878,
            "longitude": 30.0159,
            "description": "A palace, museum and extensive gardens in the Montaza district of Alexandria, Egypt."
        },
        # Hurghada
        {
            "name": "Giftun Island Snorkeling",
            "gov_name": "Hurghada",
            "city": "Hurghada",
            "categories": ["nature", "adventure", "relaxation"],
            "average_cost": 800,
            "visit_duration_hours": 6.0,
            "opening_time": datetime.time(8, 0),
            "closing_time": datetime.time(16, 0),
            "best_time": "morning",
            "popularity": 5,
            "latitude": 27.2167,
            "longitude": 33.9333,
            "description": "A boat trip to Giftun Island for snorkeling, swimming, and relaxing on sandy beaches."
        },
        {
            "name": "Hurghada Marina",
            "gov_name": "Hurghada",
            "city": "Hurghada",
            "categories": ["entertainment", "shopping", "relaxation"],
            "average_cost": 0,
            "visit_duration_hours": 2.0,
            "opening_time": datetime.time(10, 0),
            "closing_time": datetime.time(23, 59),
            "best_time": "evening",
            "popularity": 5,
            "latitude": 27.2227,
            "longitude": 33.8427,
            "description": "A beautiful promenade with yachts, cafes, restaurants, and shops."
        }
    ]

    for item in (cairo_giza_attractions + other_attractions):
        gov = gov_map[item["gov_name"]]
        Attraction.objects.update_or_create(
            name=item["name"],
            governorate=gov,
            defaults={
                "city": item["city"],
                "categories": item["categories"],
                "average_cost": item["average_cost"],
                "visit_duration_hours": item["visit_duration_hours"],
                "opening_time": item["opening_time"],
                "closing_time": item["closing_time"],
                "best_time": item["best_time"],
                "popularity": item["popularity"],
                "latitude": item["latitude"],
                "longitude": item["longitude"],
                "description": item["description"]
            }
        )

    # Seed Hotels (from hotels.json + others)
    cairo_giza_hotels = [
        {"name": "Marriott Mena House", "gov_name": "Cairo", "city": "Cairo", "price_per_night": 400, "rating": 4.5, "category": "luxury", "latitude": 29.9967, "longitude": 31.1328},
        {"name": "Steigenberger Hotel El Tahrir", "gov_name": "Cairo", "city": "Cairo", "price_per_night": 200, "rating": 4.0, "category": "mid-range", "latitude": 30.0444, "longitude": 31.2357},
        {"name": "Ramses Hilton", "gov_name": "Cairo", "city": "Cairo", "price_per_night": 250, "rating": 4.2, "category": "mid-range", "latitude": 30.0548, "longitude": 31.2318},
        {"name": "Arabian Nights Hostel", "gov_name": "Cairo", "city": "Cairo", "price_per_night": 50, "rating": 3.8, "category": "budget", "latitude": 30.0512, "longitude": 31.2421},
        {"name": "Safari Hostel", "gov_name": "Cairo", "city": "Cairo", "price_per_night": 60, "rating": 4.0, "category": "budget", "latitude": 30.0523, "longitude": 31.2403},
        {"name": "Kempinski Nile Hotel", "gov_name": "Cairo", "city": "Cairo", "price_per_night": 350, "rating": 4.6, "category": "luxury", "latitude": 30.0607, "longitude": 31.2186},
        {"name": "Le Meridien Pyramids", "gov_name": "Giza", "city": "Giza", "price_per_night": 180, "rating": 4.1, "category": "mid-range", "latitude": 29.9972, "longitude": 31.1371}
    ]

    other_hotels = [
        # Luxor
        {"name": "Sofitel Winter Palace Luxor", "gov_name": "Luxor", "city": "Luxor", "price_per_night": 350, "rating": 4.7, "category": "luxury", "latitude": 25.6987, "longitude": 32.6386},
        {"name": "Hilton Luxor Resort & Spa", "gov_name": "Luxor", "city": "Luxor", "price_per_night": 280, "rating": 4.6, "category": "luxury", "latitude": 25.7275, "longitude": 32.6583},
        {"name": "Iberotel Luxor", "gov_name": "Luxor", "city": "Luxor", "price_per_night": 120, "rating": 4.1, "category": "mid-range", "latitude": 25.6912, "longitude": 32.6322},
        {"name": "Bob Marley House Sherif Hotel", "gov_name": "Luxor", "city": "Luxor", "price_per_night": 35, "rating": 4.0, "category": "budget", "latitude": 25.6961, "longitude": 32.6410},
        # Alexandria
        {"name": "Four Seasons Hotel Alexandria", "gov_name": "Alexandria", "city": "Alexandria", "price_per_night": 500, "rating": 4.8, "category": "luxury", "latitude": 31.2435, "longitude": 29.9657},
        {"name": "Cecil Hotel (Steigenberger)", "gov_name": "Alexandria", "city": "Alexandria", "price_per_night": 220, "rating": 4.3, "category": "luxury", "latitude": 31.2009, "longitude": 29.8998},
        {"name": "Windsor Palace Hotel", "gov_name": "Alexandria", "city": "Alexandria", "price_per_night": 110, "rating": 4.0, "category": "mid-range", "latitude": 31.2012, "longitude": 29.9010},
        {"name": "Ithaka Hostel", "gov_name": "Alexandria", "city": "Alexandria", "price_per_night": 30, "rating": 4.2, "category": "budget", "latitude": 31.2023, "longitude": 29.9034},
        # Hurghada
        {"name": "Baron Palace Sahl Hasheesh", "gov_name": "Hurghada", "city": "Hurghada", "price_per_night": 450, "rating": 4.8, "category": "luxury", "latitude": 27.0423, "longitude": 33.8988},
        {"name": "Sunrise Crystal Bay Resort", "gov_name": "Hurghada", "city": "Hurghada", "price_per_night": 300, "rating": 4.7, "category": "luxury", "latitude": 27.1278, "longitude": 33.8245},
        {"name": "Arabia Azur Resort", "gov_name": "Hurghada", "city": "Hurghada", "price_per_night": 130, "rating": 4.2, "category": "mid-range", "latitude": 27.2345, "longitude": 33.8478},
        {"name": "Hurghada Backpackers", "gov_name": "Hurghada", "city": "Hurghada", "price_per_night": 25, "rating": 4.0, "category": "budget", "latitude": 27.2512, "longitude": 33.8123}
    ]

    for item in (cairo_giza_hotels + other_hotels):
        gov = gov_map[item["gov_name"]]
        Hotel.objects.update_or_create(
            name=item["name"],
            governorate=gov,
            defaults={
                "city": item["city"],
                "price_per_night": item["price_per_night"],
                "rating": item["rating"],
                "category": item["category"],
                "latitude": item["latitude"],
                "longitude": item["longitude"]
            }
        )

    # Seed Restaurants (from restaurants.json + others)
    cairo_giza_restaurants = [
        {"name": "Abou Tarek", "gov_name": "Cairo", "city": "Cairo", "cuisine": "Egyptian", "average_meal_cost": 80, "rating": 4.5, "specialty": "Koshari", "latitude": 30.0509, "longitude": 31.2435},
        {"name": "Sequoia", "gov_name": "Cairo", "city": "Cairo", "cuisine": "Mediterranean", "average_meal_cost": 250, "rating": 4.3, "specialty": "Seafood", "latitude": 30.0607, "longitude": 31.2186},
        {"name": "Zooba", "gov_name": "Cairo", "city": "Cairo", "cuisine": "Egyptian", "average_meal_cost": 120, "rating": 4.4, "specialty": "Street Food", "latitude": 30.0620, "longitude": 31.2119},
        {"name": "Felfela", "gov_name": "Cairo", "city": "Cairo", "cuisine": "Egyptian", "average_meal_cost": 100, "rating": 4.2, "specialty": "Traditional Egyptian", "latitude": 30.0448, "longitude": 31.2353},
        {"name": "Andrea El Mariouteya", "gov_name": "Giza", "city": "Giza", "cuisine": "Egyptian", "average_meal_cost": 150, "rating": 4.3, "specialty": "Grilled Chicken", "latitude": 29.9889, "longitude": 31.1264},
        {"name": "Kazouza", "gov_name": "Cairo", "city": "Cairo", "cuisine": "Egyptian", "average_meal_cost": 90, "rating": 4.1, "specialty": "Traditional Food", "latitude": 30.0634, "longitude": 31.2156},
        {"name": "The Smokery", "gov_name": "Cairo", "city": "Cairo", "cuisine": "International", "average_meal_cost": 200, "rating": 4.2, "specialty": "Fusion", "latitude": 30.0615, "longitude": 31.2139}
    ]

    other_restaurants = [
        # Luxor
        {"name": "Sofra Restaurant & Cafe", "gov_name": "Luxor", "city": "Luxor", "cuisine": "Egyptian", "average_meal_cost": 150, "rating": 4.5, "specialty": "Traditional Egyptian", "latitude": 25.6948, "longitude": 32.6366},
        {"name": "Al-Sahaby Lane Restaurant", "gov_name": "Luxor", "city": "Luxor", "cuisine": "Egyptian/Middle Eastern", "average_meal_cost": 130, "rating": 4.4, "specialty": "Camel Burger & Mezze", "latitude": 25.6997, "longitude": 32.6396},
        {"name": "Gerda's Garden", "gov_name": "Luxor", "city": "Luxor", "cuisine": "European/Egyptian", "average_meal_cost": 160, "rating": 4.3, "specialty": "Steaks & Egyptian dishes", "latitude": 25.6888, "longitude": 32.6315},
        # Alexandria
        {"name": "Fish Market", "gov_name": "Alexandria", "city": "Alexandria", "cuisine": "Seafood", "average_meal_cost": 350, "rating": 4.4, "specialty": "Grilled Sea Bass", "latitude": 31.2115, "longitude": 29.8902},
        {"name": "Greek Club Restaurant", "gov_name": "Alexandria", "city": "Alexandria", "cuisine": "Greek/Seafood", "average_meal_cost": 300, "rating": 4.3, "specialty": "Fried Calamari & Mezze", "latitude": 31.2128, "longitude": 29.8837},
        {"name": "Abou Farha", "gov_name": "Alexandria", "city": "Alexandria", "cuisine": "Egyptian/Grilled", "average_meal_cost": 120, "rating": 4.1, "specialty": "Kebab & Kofta", "latitude": 31.2224, "longitude": 29.9234},
        {"name": "Delices Café", "gov_name": "Alexandria", "city": "Alexandria", "cuisine": "Patisserie/Café", "average_meal_cost": 90, "rating": 4.5, "specialty": "French pastries & coffee", "latitude": 31.2001, "longitude": 29.9004},
        # Hurghada
        {"name": "Star Fish Restaurant", "gov_name": "Hurghada", "city": "Hurghada", "cuisine": "Seafood", "average_meal_cost": 250, "rating": 4.4, "specialty": "Singary Fish", "latitude": 27.2289, "longitude": 33.8345},
        {"name": "Moby Dick", "gov_name": "Hurghada", "city": "Hurghada", "cuisine": "International/Steakhouse", "average_meal_cost": 220, "rating": 4.3, "specialty": "Camel Steak", "latitude": 27.2267, "longitude": 33.8378},
        {"name": "El Halaka", "gov_name": "Hurghada", "city": "Hurghada", "cuisine": "Seafood", "average_meal_cost": 180, "rating": 4.2, "specialty": "Seafood Soup & Grilled Shrimp", "latitude": 27.2234, "longitude": 33.8410}
    ]

    for item in (cairo_giza_restaurants + other_restaurants):
        gov = gov_map[item["gov_name"]]
        Restaurant.objects.update_or_create(
            name=item["name"],
            governorate=gov,
            defaults={
                "city": item["city"],
                "cuisine": item["cuisine"],
                "average_meal_cost": item["average_meal_cost"],
                "rating": item["rating"],
                "specialty": item["specialty"],
                "latitude": item["latitude"],
                "longitude": item["longitude"]
            }
        )

def remove_data(apps, schema_editor):
    Governorate = apps.get_model('attractions', 'Governorate')
    Attraction = apps.get_model('attractions', 'Attraction')
    Hotel = apps.get_model('attractions', 'Hotel')
    Restaurant = apps.get_model('attractions', 'Restaurant')

    Restaurant.objects.all().delete()
    Hotel.objects.all().delete()
    Attraction.objects.all().delete()
    Governorate.objects.all().delete()

class Migration(migrations.Migration):

    dependencies = [
        ('attractions', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(seed_data, reverse_code=remove_data),
    ]
