# Generated by Django 6.0.6 on 2026-07-01 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attractions', '0002_auto_20260625_1354'),
    ]

    operations = [
        migrations.AddField(
            model_name='attraction',
            name='image_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='image_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='image_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
